-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 22:52:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` VARCHAR(36) NOT NULL,
  `nombreYApellido` VARCHAR(25) NOT NULL,
  `nombreUsuario` VARCHAR(25) NULL,
  `fechaDeNacimiento` DATE NOT NULL,
  `domicilio` VARCHAR(25) NULL,
  `contraseña` VARCHAR(60) NOT NULL,
  `email` VARCHAR(25) NOT NULL,
  `imagen` VARCHAR(50) NOT NULL,
  `tipoDeUsuario` INT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorias` (
  `idCategorias` INT NOT NULL,
  `nombre` VARCHAR(20) NULL,
  `idCategoriasM` INT NOT NULL,
  PRIMARY KEY (`idCategorias`),
  CONSTRAINT `fk_Categorias_Categorias`
    FOREIGN KEY (`idCategoriasM`)
    REFERENCES `mydb`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Categorias_Categorias_idx` ON `mydb`.`Categorias` (`idCategoriasM` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`tipoDeEnsenianza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoDeEnsenianza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoDeEnsenianza` (
  `idtipoDeEnsenianza` INT NOT NULL,
  `nombre` VARCHAR(25) NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idtipoDeEnsenianza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cursos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cursos` (
  `idCursos` VARCHAR(36) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `certificacion` TINYINT NOT NULL,
  `valoracion` DOUBLE NULL,
  `actualizacion` DATE NOT NULL,
  `idCategorias` INT NOT NULL,
  `idtipoDeEnsenianza` INT NOT NULL,
  `idUsuarios` CHAR(36) NOT NULL,
  PRIMARY KEY (`idCursos`),
  CONSTRAINT `fk_Cursos_Categorias1`
    FOREIGN KEY (`idCategorias`)
    REFERENCES `mydb`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_tipoDeEnsenianza1`
    FOREIGN KEY (`idtipoDeEnsenianza`)
    REFERENCES `mydb`.`tipoDeEnsenianza` (`idtipoDeEnsenianza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_Usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cursos_Categorias1_idx` ON `mydb`.`Cursos` (`idCategorias` ASC);

CREATE INDEX `fk_Cursos_tipoDeEnsenianza1_idx` ON `mydb`.`Cursos` (`idtipoDeEnsenianza` ASC);

CREATE INDEX `fk_Cursos_Usuarios1_idx` ON `mydb`.`Cursos` (`idUsuarios` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`Votos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Votos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Votos` (
  `idVotos` INT NOT NULL,
  `calificacion` INT NULL,
  `idCursos` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`idVotos`),
  CONSTRAINT `fk_Votos_Cursos1`
    FOREIGN KEY (`idCursos`)
    REFERENCES `mydb`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Votos_Cursos1_idx` ON `mydb`.`Votos` (`idCursos` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`Carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Carrito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Carrito` (
  `idCarrito` INT NOT NULL,
  `total` DOUBLE NULL,
  `Usuarios_idUsuarios` CHAR(36) NOT NULL,
  PRIMARY KEY (`idCarrito`),
  CONSTRAINT `fk_Carrito_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Carrito_Usuarios1_idx` ON `mydb`.`Carrito` (`Usuarios_idUsuarios` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`Baul`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Baul` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Baul` (
  `idBaul` INT NOT NULL,
  `Usuarios_idUsuarios` CHAR(36) NOT NULL,
  PRIMARY KEY (`idBaul`),
  CONSTRAINT `fk_Baul_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Baul_Usuarios1_idx` ON `mydb`.`Baul` (`Usuarios_idUsuarios` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Cursos_Baul`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cursos_Baul` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cursos_Baul` (
  `Cursos_idCursos` VARCHAR(36) NOT NULL,
  `Baul_idBaul` INT NOT NULL,
  `idCursos_Baul` INT NOT NULL,
  PRIMARY KEY (`idCursos_Baul`),
  CONSTRAINT `fk_Cursos_has_Baul_Cursos1`
    FOREIGN KEY (`Cursos_idCursos`)
    REFERENCES `mydb`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Baul_Baul1`
    FOREIGN KEY (`Baul_idBaul`)
    REFERENCES `mydb`.`Baul` (`idBaul`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cursos_has_Baul_Baul1_idx` ON `mydb`.`Cursos_Baul` (`Baul_idBaul` ASC);

CREATE INDEX `fk_Cursos_has_Baul_Cursos1_idx` ON `mydb`.`Cursos_Baul` (`Cursos_idCursos` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`Cursos_Carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cursos_Carrito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cursos_Carrito` (
  `Cursos_idCursos` VARCHAR(36) NOT NULL,
  `Carrito_idCarrito` INT NOT NULL,
  `idCursos_Carrito` INT NOT NULL,
  PRIMARY KEY (`idCursos_Carrito`),
  CONSTRAINT `fk_Cursos_has_Carrito_Cursos1`
    FOREIGN KEY (`Cursos_idCursos`)
    REFERENCES `mydb`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Carrito_Carrito1`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `mydb`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cursos_has_Carrito_Carrito1_idx` ON `mydb`.`Cursos_Carrito` (`Carrito_idCarrito` ASC) ;

CREATE INDEX `fk_Cursos_has_Carrito_Cursos1_idx` ON `mydb`.`Cursos_Carrito` (`Cursos_idCursos` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`Registrados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Registrados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Registrados` (
  `Cursos_idCursos` VARCHAR(36) NOT NULL,
  `Usuarios_idUsuarios` CHAR(36) NOT NULL,
  `idRegistrados` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idRegistrados`),
  CONSTRAINT `fk_Cursos_has_Usuarios_Cursos1`
    FOREIGN KEY (`Cursos_idCursos`)
    REFERENCES `mydb`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Usuarios_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cursos_has_Usuarios_Usuarios1_idx` ON `mydb`.`Registrados` (`Usuarios_idUsuarios` ASC) ;

CREATE INDEX `fk_Cursos_has_Usuarios_Cursos1_idx` ON `mydb`.`Registrados` (`Cursos_idCursos` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
